name: Pruebas de Regresion - Cupones

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          python -m venv venv
          pip install -r requirements.txt
      
      - name: Ejecutar Tests
        run: |
           pytest
